// <auto-generated />
using System;
using CuddlyWombat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CuddlyWombat.Migrations
{
    [DbContext(typeof(CuddlyWombatContext))]
    [Migration("20200526133236_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CuddlyWombat.Models.Item", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid?>("MenuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CuddlyWombat.Models.JItemMenu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ItemID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MenuID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MenuID1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ItemID1");

                    b.HasIndex("MenuID1");

                    b.ToTable("ItemMenu");
                });

            modelBuilder.Entity("CuddlyWombat.Models.Menu", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("CuddlyWombat.Models.Item", b =>
                {
                    b.HasOne("CuddlyWombat.Models.Menu", null)
                        .WithMany("ItemsList")
                        .HasForeignKey("MenuID");
                });

            modelBuilder.Entity("CuddlyWombat.Models.JItemMenu", b =>
                {
                    b.HasOne("CuddlyWombat.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID1");

                    b.HasOne("CuddlyWombat.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID1");
                });
#pragma warning restore 612, 618
        }
    }
}
